name: Prettier code formatter

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

permissions:
  contents: write
  workflows: write

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4

      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid

      - name: Run Prettier (auto‑fix) 🧹
        run: npx prettier . --write

      - name: Commit changes 📝
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply Prettier formatting'
